### ISSUE TITLE
Fix report: QGDsolver and hybridCentralSolvers + Intel ICX (icpx) + OpenFOAM v2312

### ISSUE THREAD

**Issue by kol1978** [unicfdlab/QGDsolver#54]
Полный лог сборки: [log.QGD.md] (https://github.com/kol1978/Backward-Facing/blob/main/QGDsolver/log.QGD.md)
Лог с ошибками:  [log.icpx_v2312_2026-09-11](https://github.com/kol1978/Backward-Facing/blob/main/QGDsolver/log.icpx_v2312_2026-09-11)
Отчёт об исправлениях: QGDsolver и hybridCentralSolvers + Intel ICX (icpx) + OpenFOAM v2312 :  [Bug-report-QGDsolver.md] (https://github.com/kol1978/Backward-Facing/blob/main/Bug-report-QGDsolver.md)

Багрепорт: [Compiler_OpenFOAM-Version_Fix.md)] (https://github.com/kol1978/Backward-Facing/blob/main/Compiler_OpenFOAM-Version_Fix.md)

### Description

`QGDsolver` fails to compile with Intel ICX compiler (oneAPI 2026.1.1, LLVM-based) due to ambiguous implicit conversion from `tmp<surfaceVectorField>` to `surfaceVectorField`. The same issue affects `hybridCentralSolvers` (`vofTwoPhaseCentralFoamEqns.C`).

GCC compiles the code without errors. This is a known long-standing issue with Clang/LLVM-based compilers and OpenFOAM's `tmp<T>` class — see [References](#8-references) below.

### Environment

```
Compiler:     Intel(R) oneAPI DPC++/C++ Compiler 2026.1.1 (2026.1.1.20260724)
Target:       x86_64-unknown-linux-gnu
LLVM backend: 18+
OpenFOAM:     v2312 (api=2312, patch=0)
OS:           Linux x86_64
Platform:     linux64IcxDPInt64Opt
```

### Error

```
leastSquaresStencil.C:147:27: error: conversion from 'tmp<surfaceVectorField>' to 'surfaceVectorField' is ambiguous
  147 |     surfaceVectorField gradComp0col = Grad(iVF.component(0));
      |                           ^          ~~~~~~~~~~~~~~~~~~~~~~~~
OpenFOAM-v2312/src/OpenFOAM/lnInclude/tmp.H:320:9: note: candidate function
  320 |         operator const T&() const { return cref(); }
OpenFOAM-v2312/src/OpenFOAM/lnInclude/GeometricField.H:345:9: note: candidate constructor
  345 |         GeometricField

leastSquaresStencil.C:148:27: error: conversion from 'tmp<surfaceVectorField>' to 'surfaceVectorField' is ambiguous
  148 |     surfaceVectorField gradComp1col = Grad(iVF.component(1));

leastSquaresStencil.C:149:27: error: conversion from 'tmp<surfaceVectorField>' to 'surfaceVectorField' is ambiguous
  149 |     surfaceVectorField gradComp2col = Grad(iVF.component(2));

leastSquaresStencil.C:206:27: error: conversion from 'tmp<surfaceVectorField>' to 'surfaceVectorField' is ambiguous
  206 |     surfaceVectorField gradComp0 = Grad(iVF.component(0));

leastSquaresStencil.C:207:27: error: conversion from 'tmp<surfaceVectorField>' to 'surfaceVectorField' is ambiguous
  207 |     surfaceVectorField gradComp1 = Grad(iVF.component(1));

leastSquaresStencil.C:208:27: error: conversion from 'tmp<surfaceVectorField>' to 'surfaceVectorField' is ambiguous
  208 |     surfaceVectorField gradComp2 = Grad(iVF.component(2));

6 errors generated.
```

### Root cause

OpenFOAM's `tmp<T>` class provides two conversion paths to `T`:

- **Conversion operator:** `tmp::operator const T&() const`
- **Constructor:** `GeometricField(const tmp<GeometricField>&)`

For copy-initialization (`Type x = expr;`), the C++ standard considers both paths. GCC resolves the ambiguity by preferring the constructor. Clang/ICX considers both paths equally valid and reports an ambiguity.

This is a defect in the C++ standard (core issue 2077), not a compiler bug. See: Stack Overflow discussion *"Clang and GCC disagree on legality of direct-initialization with conversion operator"*.

### Affected files and lines

**File:** `fvsc/leastSquares/leastSquaresStencil.C` — 6 lines:

| Line | Code |
|------|------|
| 147 | `surfaceVectorField gradComp0col = Grad(iVF.component(0));` |
| 148 | `surfaceVectorField gradComp1col = Grad(iVF.component(1));` |
| 149 | `surfaceVectorField gradComp2col = Grad(iVF.component(2));` |
| 206 | `surfaceVectorField gradComp0 = Grad(iVF.component(0));` |
| 207 | `surfaceVectorField gradComp1 = Grad(iVF.component(1));` |
| 208 | `surfaceVectorField gradComp2 = Grad(iVF.component(2));` |

### Fix

Replace copy-initialization (`=`) with direct-initialization (`()`):

```diff
--- a/fvsc/leastSquares/leastSquaresStencil.C
+++ b/fvsc/leastSquares/leastSquaresStencil.C
@@ -147,3 +147,3 @@
-    surfaceVectorField gradComp0col = Grad(iVF.component(0));
-    surfaceVectorField gradComp1col = Grad(iVF.component(1));
-    surfaceVectorField gradComp2col = Grad(iVF.component(2));
+    surfaceVectorField gradComp0col(Grad(iVF.component(0)));
+    surfaceVectorField gradComp1col(Grad(iVF.component(1)));
+    surfaceVectorField gradComp2col(Grad(iVF.component(2)));
@@ -206,3 +206,3 @@
-    surfaceVectorField gradComp0 = Grad(iVF.component(0));
-    surfaceVectorField gradComp1 = Grad(iVF.component(1));
-    surfaceVectorField gradComp2 = Grad(iVF.component(2));
+    surfaceVectorField gradComp0(Grad(iVF.component(0)));
+    surfaceVectorField gradComp1(Grad(iVF.component(1)));
+    surfaceVectorField gradComp2(Grad(iVF.component(2)));
```

This fix:

- ✅ Does not change runtime behavior (semantically identical)
- ✅ Does not affect GCC compilation (GCC accepts both forms)
- ✅ Does not affect performance (same code generation)
- ✅ Follows the recommendation from the OpenFOAM development team (issue #3138)

### Alternative fix

Use `.cref()` to explicitly select the conversion path (as done in the preCICE adapter):

```cpp
surfaceVectorField gradComp0col = Grad(iVF.component(0)).cref();
```

This is more explicit but requires modifying every expression individually.
